# This is a basic workflow to help you get started with Actions

name: Python Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Python file
    
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

